# Big Mac Activities
Let's take a look at a familiar data set (the cost of big macs around the world) and analyse it using Jupyter Notebook and Pandas. This skillset will **_directly_** link to your assessment task.

Complete each activity stipulated in the comments by looking at the *even-more-python-for-beginners* provided on GitHub.

## Series
Complete the following pandas Series following the instructions in the comments:

In [1]:
import pandas as pd

#Create a pandas Series which contains 'Australia', 'Britain', 'New Zealand' and 'United States' and store them on separate lines in a variable, 'countries'. 
countries = pd.DataFrame([
                        'Australia',
                        'Britan',
                        'New Zealand',
                        'United States'])


#Print the series
countries

               0
0      Australia
1         Britan
2    New Zealand
3  United States

In [14]:
#Output Britain from the list using its index
countries = pd.DataFrame([
                        'Australia',
                        'Britan',
                        'New Zealand',
                        'United States'])


countries[1]

KeyError: 1

In [ ]:
#Iterate through all values in countries series using a for loop

## DataFrame
Usually we work with two-dimensional arrays. We store them using **DataFrame** in pandas. 

### Activity
Let's use a DataFrame to store more meaningful values than our countries series. Let's store the following values in a Data Frame called 'big_mac':

**Headings:** Country, Local Price, AUD Price
- `'Australia', 7.45, 7.45`
- `'Britain', 4.19, 0.0`
- `'Japan', 450, 0.0`
- `'New Zealand', 7.1, 0.0`
- `'United States', 5.58, 0.0`

**NOTE:** You'll need to look online at current rates to convert Britain, New Zealand, Japan and United States' local prices to AUD.

In [7]:
#Add a pandas DataFrame called 'big_mac' with the above values
big_mac = pd.DataFrame([
                        ['Australia', 7.45, 7.45],
                        ['Britan', 4.19, 7.93],
                        ['Japan', 450, 4],
                        ['New Zealand', 7.1, 5.9],
                        ['United States', 5.58, 7.87]
                        ],
                        columns = ['Country', 'Local price', 'AUD'])
#Print the DataFrame
big_mac

         Country  Local price   AUD
0      Australia         7.45  7.45
1         Britan         4.19  7.93
2          Japan       450.00  4.00
3    New Zealand         7.10  5.90
4  United States         5.58  7.87

## Examining pandas DataFrames

In [ ]:
#Print only the first two rows of the big_mac dataframe

In [ ]:
#Print only the last four rows of the big_mac dataframe

In [ ]:
#Print the number of rows and columns in the big_mac dataframe

In [ ]:
#Print some detailed information about the big_mac dataframe

## Querying DataFrames
Let's explore how we request data from a pandas DataFrame.

In [ ]:
#Request and output the 'Country' and 'AUD Price' columns from the big_mac DataFrame.

In [ ]:
#Use iloc to request the third row, all columns

In [ ]:
#Use iloc to request all rows, but just the 'Country' and 'AUD Price' columns

In [ ]:
#Use loc to do the same thing as the previous (Country and AUD Price all rows)